- hosts: localhost
  pre_tasks:
    - name: Update Cache
      become: true
      apt:
        update_cache: true
      tags:
        - shell
        - node
  tasks:
    - name: Install zsh, stow, git, curl, tmux, fzf
      become: true
      apt:
        pkg:
          - zsh
          - stow
          - git
          - curl
          - tmux
          - fzf
          - unzip
      tags:
        - shell
    - name: Install build-essential
      apt:
        pkg:
          - build-essential
      tags:
        - nvim
    - name: Change shell
      shell: chsh -s `which zsh`
      tags:
        - shell
    - name: Install Oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
        - shell
    - name: Download zsh theme
      shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      tags:
        - shell
    - name: Remove old .zshrc and .bashrc
      shell: rm ~/.zshrc ~/.bashrc
      tags:
        - shell
    - name: Stow dotfiles
      shell: stow home
      tags:
        - shell
        - dotfiles
    - name: Install nodejs and npm
      become: true
      apt:
        pkg:
          - nodejs
          - npm
          - yarn
      tags:
        - node
    - name: Install n for managing nodejs versions
      npm:
        name: n
        global: true
      tags:
        - node
    - name: N install lts
      shell: n lts
      tags:
        - node
    - name: Download rustup installer
      get_url:
        url: https://sh.rustup.rs
        dest: ./temp/rustup
        mode: 0755
        force: true
      tags:
        - rust
    - name: Install rust & cargo
      shell: ./temp/rustup -y
      tags:
        - rust
    - name: Download Bun installer
      get_url:
        url: https://bun.sh/install
        dest: ./temp/bun
        mode: 0755
        force: true
      tags:
        - bun
    - name: Install Bun
      shell: ./temp/bun
      tags:
        - bun
    - name: Download kitty terminal installer
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: ./temp/kitty
        mode: 0755
        force: true
      tags:
        - kitty
    - name: Install kitty terminal
      shell: ./temp/kitty
      tags:
        - kitty
    - name: Create ~/.local/bin folder to avoid stow conflicts
      shell: mkdir -p ~/.local/bin && mkdir -p ~/.local/lib
      tags:
        - kitty
        - nvim
    - name: Stow kitty
      shell: stow . -t ..
      args:
        chdir: ~/.local/kitty.app
    - name: Download Go installer
      get_url:
        url: https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
        dest: ./temp/go
        mode: 0755
        force: true
      tags:
        - go
    - name: Install Go
      become: true
      shell: rm -rf /usr/local/go && tar -C /usr/local -xzf ./temp/go
      tags:
        - go
    - name: Download neovim
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: ./temp/nvim
        mode: 0755
        force: true
      tags:
        - nvim
    - name: Install neovim
      shell: tar xzvf ./nvim-linux64.tar.gz && rm -rf ~/.local/nvim && mv ./nvim-linux64 ~/.local/nvim 
      args:
        chdir: ./temp
      tags:
        - nvim
    - name: Stow neovim
      shell: stow . -t ..
      args:
        chdir: ~/.local/nvim
      tags:
        - nvim
