- hosts: localhost
  pre_tasks:
    - name: Update Cache
      become: true
      apt:
        update_cache: true
      tags:
        - shell
        - node
    - name: Create temp folder
      ansible.builtin.file:
        state: directory
        path: ./temp
    - name: Create some folders to prevent stow conflicts
      shell: mkdir -p ~/.local/bin && mkdir -p ~/.local/lib && mkdir -p ~/.local/share/icons && mkdir -p ~/.local/share/icons/hicolor
  tasks:
    - name: install zsh
      become: true
      apt:
        pkg:
          - zsh
      tags:
        - zsh
    - name: Install stow, git, curl, tmux, fzf, and some libraries
      become: true
      apt:
        pkg:
          - stow
          - git
          - curl
          - tmux
          - fzf
          - unzip
          - libsecret-1-0
          - libsecret-1-dev
          - libglib2.0-dev
      tags:
        - shell
        - ghostty
    - name: Setup libsecret as git credential store
      shell: |
        sudo make --directory=/usr/share/doc/git/contrib/credential/libsecret
        git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
    - name: Install build-essential
      become: true
      apt:
        pkg:
          - build-essential
      tags:
        - nvim
        - rust-coreutils
    - name: Change shell to zsh
      become: true
      shell: chsh -s $(which zsh) $(whoami)
      tags:
        - zsh
    - name: Remove old .zshrc
      ansible.builtin.file:
        state: absent
        path: ~/.zshrc
      tags:
        - zsh
    - name: Remove old .bashrc
      ansible.builtin.file:
        state: absent
        path: ~/.bashrc
      tags:
        - zsh
    - name: Stow dotfiles
      shell: stow home
      tags:
        - zsh
        - dotfiles
    - name: Install nodejs and npm
      become: true
      apt:
        pkg:
          - nodejs
          - npm
          - yarn
      tags:
        - node
    - name: Install n for managing nodejs versions
      become: true
      npm:
        name: n
        global: true
      tags:
        - node
    - name: N install lts
      become: true
      shell: n lts
      tags:
        - node
    - name: Download rustup installer
      get_url:
        url: https://sh.rustup.rs
        dest: ./temp/rustup
        mode: 0755
        force: true
      tags:
        - rust
    - name: Install rust & cargo
      shell: ./temp/rustup -y
      tags:
        - rust
    - name: Install nushell
      shell: |
        cargo install nu --locked
        cargo install nu_plugin_polars --locked
        cargo install nu_plugin_formats --locked
        cargo install nu_plugin_gstat --locked
        cargo install nu_plugin_query --locked
        cargo install nu_plugin_inc --locked
      tags:
        - nushell
    - name: Download Bun installer
      get_url:
        url: https://bun.sh/install
        dest: ./temp/bun
        mode: 0755
        force: true
      tags:
        - bun
    - name: Install Bun
      shell: ./temp/bun
      tags:
        - bun
    - name: Download kitty terminal installer
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: ./temp/kitty
        mode: 0755
        force: true
      tags:
        - kitty
        - update-kitty
    - name: Install kitty terminal
      shell: ./temp/kitty
      tags:
        - kitty
        - update-kitty
    - name: Stow kitty
      shell: stow . -t ..
      args:
        chdir: ~/.local/kitty.app
      tags:
        - kitty
        - stow
    - name: Download Go installer
      get_url:
        url: https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
        dest: ./temp/go
        mode: 0755
        force: true
      tags:
        - go
    - name: Install Go
      become: true
      shell: rm -rf /usr/local/go && tar -C /usr/local -xzf ./temp/go
      tags:
        - go
    - name: Which neovim version should be installed?
      pause:
        prompt: Which neovim version should be installed? (e.g. v0.10.4)
      tags:
        - nvim
      register: nvim_version
    - name: Download neovim
      get_url:
        url: https://github.com/neovim/neovim/releases/download/{{ nvim_version.user_input }}/nvim-linux-x86_64.tar.gz
        dest: ./temp/nvim
        mode: 0755
        force: true
      tags:
        - nvim
    - name: Install neovim
      shell: tar xzvf ./nvim && rm -rf ~/.local/nvim && mv ./nvim-linux-x86_64 ~/.local/nvim
      args:
        chdir: ./temp
      tags:
        - nvim
    - name: Stow neovim
      shell: stow . -t ..
      args:
        chdir: ~/.local/nvim
      tags:
        - nvim
        - stow
    - name: Install bat
      shell: cargo install bat
      tags:
        - rust-coreutils
        - bat
    - name: Install starship
      shell: cargo install starship --locked
      tags:
        - shell
    - name: Install exa
      shell: cargo install exa
      tags:
        - rust-coreutils
        - exa
    - name: Download lazygit
      shell: |
        LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
        curl -Lo ./temp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
      tags:
        - lazygit
        - git
    - name: Unpack lazygit
      tags:
        - lazygit
        - git
      shell: tar xf ./temp/lazygit.tar.gz --directory=./temp lazygit
    - name: Install lazygit
      become: true
      tags:
        - lazygit
        - git
      shell: install ./temp/lazygit /usr/local/bin
    - name: Install nix
      shell: sh <(curl -L https://nixos.org/nix/install) --daemon
    - name: Clone Ghostty repo
      ansible.builtin.git:
        repo: https://github.com/ghostty-org/ghostty.git
        dest: ./temp/ghostty
      tags:
        - ghostty
    - name: Install ghostty dependencies
      become: true
      apt:
        pkg:
          - libgtk-4-dev
          - libadwaita-1-dev
      tags:
        - ghostty
    - name: Build Ghostty with nix
      args:
        chdir: ./temp/ghostty
      shell: nix build .#ghostty
      tags:
        - ghostty
    - name: Clone zk repo
      tags:
        - zk
      ansible.builtin.git:
        repo: https://github.com/zk-org/zk.git
        dest: ./temp/zk
    - name: Build zk
      shell: make
      args:
        chdir: ./temp/zk
      tags:
        - zk
    - name: copy zk binary
      ansible.builtin.copy:
        src: ./temp/zk/zk
        dest: ~/.local/bin/zk
        mode: '0744'
      tags:
        - zk
    - name: Install zoxide
      shell: cargo install zoxide --locked
      tags:
        - zoxide
        - rust-coreutils
    - name: Install atuin
      shell: cargo install atuin
      tags:
        - atuin
        - rust-coreutils

