- hosts: localhost
  pre_tasks:
    - name: Update Cache
      become: true
      apt:
        update_cache: true
      tags:
        - shell
        - node
    - name: Create temp folder
      ansible.builtin.file:
        state: directory
        path: ./temp
    - name: Create some folders to prevent stow conflicts
      shell: mkdir -p ~/.local/bin && mkdir -p ~/.local/lib && mkdir -p ~/.local/share/icons && mkdir -p ~/.local/share/icons/hicolor
  tasks:
    - name: Install zsh, stow, git, curl, tmux, fzf, and some libraries
      become: true
      apt:
        pkg:
          - zsh
          - stow
          - git
          - curl
          - tmux
          - fzf
          - unzip
          - libsecret-1-0
          - libsecret-1-dev
          - libglib2.0-dev
      tags:
        - shell
    - name: Setup libsecret as git credential store
      shell: |
        sudo make --directory=/usr/share/doc/git/contrib/credential/libsecret
        git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
    - name: Install build-essential
      become: true
      apt:
        pkg:
          - build-essential
      tags:
        - nvim
    - name: Change shell
      become: true
      shell: chsh -s $(which zsh) $(whoami)
      tags:
        - shell
    - name: Remove old version of oh-my-zsh
      ansible.builtin.file:
        state: absent
        path: ~/.oh-my-zsh
    - name: Install Oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
        - shell
    - name: Download zsh theme
      shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      tags:
        - shell
    - name: Remove old .zshrc
      ansible.builtin.file:
        state: absent
        path: ~/.zshrc
      tags:
        - shell
    - name: Remove old .bashrc
      ansible.builtin.file:
        state: absent
        path: ~/.bashrc
      tags:
        - shell
    - name: Stow dotfiles
      shell: stow home
      tags:
        - shell
        - dotfiles
    - name: Install nodejs and npm
      become: true
      apt:
        pkg:
          - nodejs
          - npm
          - yarn
      tags:
        - node
    - name: Install n for managing nodejs versions
      become: true
      npm:
        name: n
        global: true
      tags:
        - node
    - name: N install lts
      become: true
      shell: n lts
      tags:
        - node
    - name: Download rustup installer
      get_url:
        url: https://sh.rustup.rs
        dest: ./temp/rustup
        mode: 0755
        force: true
      tags:
        - rust
    - name: Install rust & cargo
      shell: ./temp/rustup -y
      tags:
        - rust
    - name: Download Bun installer
      get_url:
        url: https://bun.sh/install
        dest: ./temp/bun
        mode: 0755
        force: true
      tags:
        - bun
    - name: Install Bun
      shell: ./temp/bun
      tags:
        - bun
    - name: Download kitty terminal installer
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: ./temp/kitty
        mode: 0755
        force: true
      tags:
        - kitty
        - update-kitty
    - name: Install kitty terminal
      shell: ./temp/kitty
      tags:
        - kitty
        - update-kitty
    - name: Stow kitty
      shell: stow . -t ..
      args:
        chdir: ~/.local/kitty.app
      tags:
        - kitty
        - stow
    - name: Download Go installer
      get_url:
        url: https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
        dest: ./temp/go
        mode: 0755
        force: true
      tags:
        - go
    - name: Install Go
      become: true
      shell: rm -rf /usr/local/go && tar -C /usr/local -xzf ./temp/go
      tags:
        - go
    - name: Download neovim
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: ./temp/nvim
        mode: 0755
        force: true
      tags:
        - nvim
    - name: Install neovim
      shell: tar xzvf ./nvim && rm -rf ~/.local/nvim && mv ./nvim-linux64 ~/.local/nvim 
      args:
        chdir: ./temp
      tags:
        - nvim
    - name: Stow neovim
      shell: stow . -t ..
      args:
        chdir: ~/.local/nvim
      tags:
        - nvim
        - stow
    - name: Install bat
      shell: cargo install bat
      tags:
        - rust
    - name: Install starship
      shell: cargo install starship --locked
      tags:
        - shell
    - name: Install exa
      shell: cargo install exa
      tags:
        - rust
