- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
  tasks:
    - name: Install zsh, stow, git, curl, tmux, fzf
      apt:
        pkg:
          - zsh
          - stow
          - git
          - curl
          - tmux
          - fzf
          - unzip
    - name: Change shell
      shell: chsh -s `which zsh`
    - name: Install Oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: Download zsh theme
      shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    - name: Remove old .zshrc and .bashrc
      shell: rm ~/.zshrc ~/.bashrc
    - name: Stow dotfiles
      shell: stow home
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
          - yarn
    - name: Install n for managing nodejs versions
      npm:
        name: n
        global: true
    - name: N install lts
      shell: n lts
    - name: Download rustup
      get_url:
        url: https://sh.rustup.rs
        dest: ./temp/rustup
        mode: 0755
        force: true
    - name: Install rust & cargo
      shell: ./temp/rustup -y
    - name: Install Bun
      shell: curl -fsSL https://bun.sh/install | bash
